apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secrets
namespace: home
type: Opaque
stringData:
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:9b1w10d4LYQa7W+LPLWhEqolmozla2ERnrjYuDWWAr2j63NJLQkd3X8Ediq/hVxB7dZ3jn7aoDbjnw==,iv:TxxHwM8ygFPSzmZv7vH4A4bEZzSkyn0bNZMWqJBdV+Q=,tag:rFXfGao8Hkpayfsdwtzkug==,type:str]
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:6CKKN5VfiTBXojChau1U8sYZ17PgjtQfn5wIR3qOQq4=,iv:I9VqWOljXQqT5OfeSn5Dulc9rfrj1I1UlzwD6q7yJW4=,tag:isr0ctkkG2ec7MVw2GdzKg==,type:str]
  secret.yaml: ENC[AES256_GCM,data:n3Sg94FjOkLsYSidJ7+QjNvGpyeVmJhLmh+B23A6oz3hQpOmsC9m6NtytTEeAhhX7Mw2enNwxFYkLwwnPINPYDwZ9+VIbYhn/yGzp0TrQzJlc3A9EMfvyT19s0itmrJbr6409iwyDUOFyrbSf43o8aCcOTAYQwJf/WgAGcqvkkM8OtAkdBo=,iv:+VXMdGVTOZaZdrOt5OQDhR0mF6W9oGSmWqTIhJMb14k=,tag:PplWOPx5OVaRsq4TC2bD5g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbkJKSlVCdTM3NFhUMStH
        YXViUWRzWHdSalBDTm5RQU8yd010TldxTUZzCmVlZkl3Wk9DeG9rL2tTT3RuSmRV
        cHE5dkM3YXVPNU9EVWlOZUdUV1VsSkEKLS0tIGpQUks2Mm9JcjJ1VzVLV2hicFNH
        VTlNUnRKSllzN1VyNnZpeXA2VGhqZWsKCosFDh+/J5UjXoYZJb2aDlbo7WXgnBmd
        6Z/6geZ+tOxvCCMvvei4YPbVg8dMRjAqYupyqL8UplOv1HVdWEwP1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1S0d2Y3dlQzl3Q0htOVd6
        NmU2akI0eFdVUDlaOFdDajhOWHhGbWNqQ0YwCnJWS2dDNURTNXBLUUpzSGwydFZ0
        WG5RUWJFRW9UVS90endWcUlvcmtIRXcKLS0tIDFEQXFrTUhmbXpUQWF1bnRCbk5a
        aHp0RDRKbUVVRkNuQ1hVQlRTelk2SVUKvrYI8RHCvcmNuE40AX/2DyKx7kMg4iep
        yFD/8f8mRiAJ+9RcxmyZ2BjguvimPI3EZsU5hvYMzzOtMq1fJN9GMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:30:10Z"
  mac: ENC[AES256_GCM,data:w2aYx//xBHxokypN80ye9ZpTxspZ+IZB5UOTmzbK6qeGsIS/eouPMmS2gjQSw/oXU0lUtJG1jJtxyf9XcTAmIZgjxBbHTAf2bCF2hQe/0O0C2TcPu3vuJcUm/zQXsUIOPiyq+RjrKC0KOnS+5sc3zsHq+4AxRhOGIHhdnXd2unI=,iv:/NapslP5rjSu/YKrWcLl0u7bHMhYroDbZSEA2seOQKU=,tag:7TxcbfhV6OvezuOTh39ZlA==,type:str]
  version: 3.13.3
