apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secrets
  namespace: home
type: Opaque
stringData:
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:imzSWuQBApST27i1xbd4CBmZeZcUf142f6iKRuuiPabSvTyxwZsLqvuMTgx/bY2Slvl7EiKGs0epzQ==,iv:GbJto+HhH8lcg25MHkA4Sa+vBJ3UMsBJ6yY+EwDlwxU=,tag:GCXMyDKVUNt5cXnWpP+FNA==,type:str]
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:X4o43DvHCsgQOaC3Et108bvrj5S6y+TESzlQia9gaTE=,iv:uIU7SqUQA1WL922K/sr77SrOFeibjzYge3DyVgI0Gdk=,tag:/dqJSC4YZ1fONuKZk3DtSw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QllwMy9hN3cwaTdoOTFB
        K1F4cktCS2pFYWxqY0pCME1udHdIY29GMUNRCnNjUUVta0xFcWp2T2E3Q1lTNVNP
        dlEyK2lzbWtMSHRWVTJyMTdGZzlDSzQKLS0tIGhteExyT2Qra2x5VUFQdEQ2ZTkv
        ZnFYNEZ2WElwb2g5N014Mms2NHZlNlkK819NBNbV+VjMf+6uNfCLbUOsryZp8H9U
        UkDeqsWrOJIkkhD4F51QWLMEnk5XKYDJQOR5RIgj60J4EPT0W4BCgA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvL050TlpLWHowYnhpQ3BQ
        V3ozZGZrTHB2MUo3Z1Y4d2VDUHhTWFZkc2lVCkVlRytaNTFXOVF0MkQzVjYvaSs0
        ODJ5WG04alFFUkZXOHd2ZUJtdTZMSDgKLS0tIFpQT0ZsYjZlRDhwZm1NNGRUZ1ky
        RHpjakpjd0tsNEsya0hkTUNYdFlrVWcKDqWsnpiE5W1zxnfMDx8Kx5c0aN7miVv/
        yp8zU0eDIHub1i7flK+4LJJFuqBlcVOEgi/K2YVTyFBu25QnY44rBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T21:19:57Z"
  mac: ENC[AES256_GCM,data:0lilkeN4Ccv2fObQC4gzXHIBjGg10w5HuXFZYA/TNNDcSCHR1Pq0+ijMovu//Qx0GD0AeNaQKO4Le22v2iQi579yBDVkHhLhCB8eClsIQqz20az9JbO1Fy0Tf5ds2mPIIwrNpJveT7JP/JENY+i1O1JLMLOh95S+fyB1pwjaCUI=,iv:QGMF2duWoibbol3xEZnBbs3raQ3nNXtvIA4ZNRRM9Yk=,tag:UpfL+SbMeF3wjZya8fBEKg==,type:str]
  version: 3.13.3
