---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  dependsOn:
  - name: longhorn
    namespace: longhorn-system
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/prowlarr
              tag: "2.0.5.5160-ls125@sha256:4f2a6d597845b2f3e19284b1d982b3e0b4bd7c22472c2979c956aa198b83f472"
            env:
              TZ: "${TIMEZONE}"
              PUID: 1000
              PGID: 1000
            # to avoid permissions issues on volume
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
    service:
      app:
        controller: main
        ports:
            http:
              port: &port 9696
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_PUBLIC_DOMAIN}"]
        parentRefs:
          - name: traefik-gateway
            namespace: networking
            sectionName: websecure
        rules:
          - backendRefs:
              - identifier: app
                port: *port
            filters:
              - type: 'ExtensionRef'
                extensionRef:
                  group: 'traefik.io'
                  kind: 'Middleware'
                  name: 'forwardauth-authelia'
    networkpolicies:
      default-deny:
        controller: main
        policyTypes: [Ingress, Egress]
        rules: {}
      allow-dns:
        controller: main
        policyTypes: [Egress]
        rules:
          egress:
            - ports:
                - port: 53
                  protocol: UDP
                - port: 53
                  protocol: TCP
              to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
      allow-traefik-ingress:
        controller: main
        policyTypes: [Ingress]
        rules:
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: networking
      allow-auth-ingress:
        controller: main
        policyTypes: [Ingress]
        rules:
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: auth
      allow-arr-ingress:
        controller: main
        policyTypes: [Ingress]
        rules:
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: media
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/instance: sonarr
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: media
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/instance: radarr
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: media
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/instance: lidarr
              ports:
                - port: 9696
                  protocol: TCP
      allow-monitoring-ingress:
        controller: main
        policyTypes: [Ingress]
        rules:
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: monitoring
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: prometheus-blackbox-exporter
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: monitoring
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: uptime-kuma
              ports:
                - port: 9696
                  protocol: TCP
      allow-external-egress:
        controller: main
        policyTypes: [Egress]
        rules:
          egress:
            - ports:
                - port: 443
                  protocol: TCP
              to:
                - ipBlock:
                    cidr: 0.0.0.0/0
                    except:
                      - 10.0.0.0/8
                      - 172.16.0.0/12
                      - 192.168.0.0/16
    persistence:
      config:
        existingClaim: pvc-prowlarr
        advancedMounts:
          main:
            app:
              - path: /config
