apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
  namespace: networking
data:
  config.yaml: |-
    ---
    server_url: https://hs.${SECRET_PUBLIC_DOMAIN}
    listen_addr: 0.0.0.0:8080
    unix_socket: /var/lib/headscale/headscale.sock
    metrics_listen_addr: 0.0.0.0:9091

    noise:
      private_key_path: /var/lib/headscale/noise_private.key

    derp:
      server:
        enabled: false
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      auto_update_enabled: true
      update_frequency: 24h

    database:
      type: sqlite
      sqlite:
        path: /var/lib/headscale/db.sqlite

    log:
      level: info

    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48

    dns:
      magic_dns: true
      base_domain: tailnet.internal
      override_local_dns: false
      nameservers:
        global:
          - 1.1.1.1
          - 8.8.8.8

    policy:
      mode: file
      path: /etc/headscale/policy.hujson
