apiVersion: v1
kind: Secret
metadata:
  name: tailscale-proxy-prometheus-auth
  namespace: networking
type: Opaque
stringData:
  #ENC[AES256_GCM,data:8LCtXZJf2AgtOEJddsoyjbh7Sm30sA1c15fKUkUzs1DNSaVG99APfSo7,iv:2W7yTGS/X+zzYvzWvA6lWxYhnglgt5jMrADnsA2Dpio=,tag:vxYKax7pSAeir+KsRr7SWg==,type:comment]
  #ENC[AES256_GCM,data:Uvwf/4fMPRb7zYD85oinb5vLMQ+6xIYrGKbP3GsfzFlKIQm5LdiL6UeiB5W6VOPL9RKvIZajZaaxGYgfkQyX3sZPh01EqaTZNKTvKuV/wNiSF0Npzk5aS4WI,iv:xaX6rtQB3xXG49zF/Wne1CwJ7SfIzUgXWral+t/IhMA=,tag:AvqcOZv+l9VLrzbOe0+2nA==,type:comment]
  #ENC[AES256_GCM,data:EFtuX2H/D2WDrWTmOaN5QQTel/ZRbAVQY1kSmNnnPcMbkGLItaKTbWTp9I1ot5WXSjN4dCwgmGPKsjYEzmtPDAYvd+nqBmd1,iv:rusGJmd0UX6eTqXMekui8F/WyxHCiXRLjTtcf4sqqk0=,tag:VBkwxDPlXQouto1EXmJ8DQ==,type:comment]
  #ENC[AES256_GCM,data:sFYhK55WzrCNrTuHn5iSCSVlhg45190XUyKwLAiaiFNcs9kaW6NR8ITrMQGtGIsdTdUWAuP2fUMn62QSA5qCQa8zQpKlPlMM5GpaOB4=,iv:q5rlgHsUTvtiirKOkBtUhM9RI5Kcehua7NoSB+PsqCg=,tag:QAxkEQ2mi4O+dFIjIckzqw==,type:comment]
  TS_AUTHKEY: ENC[AES256_GCM,data:92ydg4kZ+cC2XerVK/tAwRAbjCb3YcmFGF2HDl4LvCNSeMaW7B3wgIvCU2SjiPO+7oveXpEu30rD7Y4gBpfgAZehMOnz4QkbTgqP4ObYbWJx7tfwkRe43g==,iv:FZeRsiXl47Zo6WwSe8tdJjvMW8qYqmiHCcweMq4GTv8=,tag:ZIZEqxa2fCb73+BnyjKYkA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TXBrUjRydVZwOGtXbWpJ
        SlVqelpMdjJGTjAzYXIxK0tVc2F4Z3dBelNJCkZ6TW1QQmxvTUxTanFrYzUrdkxZ
        NUp6SSs3ejFUSXQ5QkJXYTlKdkNyMkUKLS0tIGZsWFJ5TnkwZ0hOYWJFQ3hsYTRZ
        eTM2c2xBVkFnclBxLzJaNDN5bDZZVTQKr/uz6/enOOjAkprLKKi8/+u2sUf29IxP
        q2TJEy8xNi4LfaspX3m4Ukt9O9bJyp2k86h6/UUXk5sLLnSmkAk34A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Zk96aUEzTTJCZ2tJbno5
        c2o2Z1hvcS9RMk1nclAyTGE0cGVIRkNHL21NCkRGeFI2aG9uODE2Mm92YktLYmFW
        b01PSng4NVdzWFpqTlExQmgzc2VNRDQKLS0tIG1vUkN0VnVRRTBJOG1lZ09uOTlY
        WlBqQklRbWtSMitXMW9BYmJQc0t6cWMKIYkhU+8kYmfJqWjXPs+CkmKcvnfSYvt9
        MHUqypnMfRMOMgWqNCcxgzc4PUeN3HKR+OTzw0tCWlXc6JDLWWLajA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T07:33:49Z"
  mac: ENC[AES256_GCM,data:DSpwHzRR7E+Pn2+t4dctuWUr9yzwZq6/4hV0ZhwI5bLSSeT3eHW71Vm7c1ST2rP7UMQrSgz8fY3Ao9ARUJSdGIJ7gcct7ByxuwFuE1GNQOpmV8Gvd+/NcbOGRn8q5MAG/q+fvVE2GQYp36p8mcXBwaoDwcNF7loqf+Bdl6tDJNM=,iv:V2FMFHvuOa0UuXRtVrBXr7h0RHoA0eWtTuh7f65uIsM=,tag:GrYo7uOUv3CHuxo8IdVZNA==,type:str]
  version: 3.13.3
