apiVersion: v1
kind: Secret
metadata:
  name: tailscale-proxy-blocky-auth
  namespace: networking
type: Opaque
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:H1mQU5WStLnDWcShdbGsXYPpzXOtURmZbn4Sms3wOGx434woq2a794mbY4eQFK/A3QtJQSAZI2Zdqy15ereTtUOgj855h+GyS4L36oA5crHOOoqtQl0uJw==,iv:F/LG5BPQAbg9i9Erkri349yQYMOuE9OTWWdcTxcQBFE=,tag:H+sxuFAU9qkJ+a6M6Wsdpw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSTNIOTVRZ041WWIwMWJx
        bWY0b0RMeWR5bzdwSTY2R25xMkh2VFVJRldjCi9aZVp1cGJDZE9zSnJXaGlvVENI
        NEpuL1VQTEZTT29sTEwvSVFoVzZ6T28KLS0tIDAxaFVCbEQzQ3V3MzNidVBhenBv
        UGh2aTg5aXFuNnluczhyQWZZQTlJSUkKgYQ2NFUhMbCwjAkFE/GcWTuvKqRDAfs1
        zavUM35FCMkAB+GlJEi5KAPhsIhF1Q+dCb5q36fDRxs5DleQjR8Kjw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aVJkTXRkanlRSERtaG1G
        V3EvaVlpLzdBM3lSdUxBNmZSQW5GK0ZTMHgwClZDMHBuRkdWOUc1M2V4Z054dll3
        NGlkcnFBNm5uNGxFMEh3Q09lSTVONkUKLS0tIEFtbTBndkpONlRpb2w5WTZNUWlu
        YTczdGVGTUg5L2dFNUJMVUc0eWh3T1kKwNJ48031bBR9GDqsJTUoi4X7Gauk9cEP
        HcQspWRwP9NSnfkLf24xpx2Q/0JI31SnLjLE73qqKmGDR6E0F3DlDg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T09:45:11Z"
  mac: ENC[AES256_GCM,data:qMxvXeEvT1U+EjFQA4XI14/4elKfx4zw41P5I9qlcXrwlJ3mgZ6OHwUJi1u+Pb5qZ9I53NPZfZw4z8dG1VNgGAb2+x7cEevF3JkKf2m4ZMRGR/ybycs8Skgm/RiWbGIAgxYw0HogI3ZsIU3sEf4EO2U8B6/wzJDd2MgIA4G3yHI=,iv:23emQcAjSfm8cmsaLJKgY1s/OOCI+tXnGxE1Wh6Krzw=,tag:bIQGpZGLWMbxtJ4XtLpMjw==,type:str]
  version: 3.13.3
