apiVersion: v1
kind: Secret
metadata:
  name: tailscale-router-auth
  namespace: networking
type: Opaque
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:u69+idhoW3oHLpABVwrL+BjvZ4Nd/F5Ur1RNvo5OBi/XEuBAfrb4izVR76LzIFG8ATUSQktCtMVS+CRAA1DzsDiRCdYHuJ71LKjWavJ9B7WrLpLAs5ResA==,iv:PuM08UDhJ8sxMppoFqxxoz4VIv++wFdy3cSXDnIOV44=,tag:v/IoJsLR90thjCsTwveuyg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WTZ2Y2lrVWcybVB6WDZW
        VnZieS9raVpnY3dxUjluL0VnK3NnTkRpS3hJCjB2V2lvam43R0hHMkJzeWViOGRl
        OVdyWTFKb1R2SGpRL2svTlRWT1lsM0UKLS0tIGNmZ083RXd6WVVpdDB2Q2s3SFp3
        Rjc3QzRZQU9DTmpZTEZsczlCU1cySFkKUEVNu/OWZt88b+6vyZ+sFIgJAW+rxc2Z
        I2GwLmBrIRWP0whE4Fkv40tgtf8AIgJiBPE3KEJPGgZVumHLFg1CdQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMXhkRmJ3NW9NQmVOb2Z6
        YjBVL2NEY1RqVWRXOHg1SEtlUlNxTmNETW5RCmxzM0luVlJSblJHRVRGSzVyTWlU
        UnVKQ1pibWxVdktlSHcxUlNyZmtkckkKLS0tIFVsZFlHWk5GcXNpT3B4M1BxdVRG
        eXNibTBuZDlXWUZkUmo2ek1heGt4THcK4vkvuYpMSF1PAVRyJTgR/BLfgzvXXYZe
        yU0BYVAvn1RXM22ltn326h0WbcHQJnemsu8CtgbdxQ1edhYTDrzbXg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-28T19:44:07Z"
  mac: ENC[AES256_GCM,data:0OW2+oN/fTSycqxJVsLLh8u2VdjO4OLVaW4ab0061WxTmWELahb5wnZXkXg3OCdgnxYBdCrviov+Bykz5D9HZbk64JI9aw0n5Vqz3OPWzxxVhBBLlwRG9fPS2+6/uL5q5Juacv9ZWG1EX831GnijKq1IDPo4/TC1t4ZaCieuOqY=,iv:jJuZe9JgZzFBB3zZtKoJ7dhw++j4WECMNyQXODR6rW8=,tag:BpbWF0RAV01LX5SatW3G9w==,type:str]
  version: 3.13.3
