apiVersion: v1
kind: Secret
metadata:
    name: tailscale-proxy-loki-auth
    namespace: networking
type: Opaque
stringData:
    #ENC[AES256_GCM,data:SaurQ+26zDAVjicauyszer1WvCQ7qXlsQk8n8Qpye4Hmqbb0pnEwXqFy,iv:NHMBH6OBdGkuZ6UnzjPuieK3HXqC9W6/3v9mFoEwz6w=,tag:78j3Wh1puz8CuiFME9hzzg==,type:comment]
    #ENC[AES256_GCM,data:Ri2mmhIPs4/E5FbQmiuxrx9uBJ3UBhn9ZyMc/7atHwMH3Jl0iKcPyzBW5QikqbxHV9cKtlbkckuVoyIM0hCMytszovZf+ACrYBqLur8Rm8Sk+/1O,iv:OCSN+/3BAIGkOEJ19YQZHQjS0iZfiW8iJ1Oob94+410=,tag:Zccp/BN8QB2ggue4c58eDA==,type:comment]
    #ENC[AES256_GCM,data:itqdzbmI6vBbYfwU8sNVgYe1qjW1ifw/4QPXHU/23XK7tBaPYqy3IEWCdSJlEm9xWFx9wIEF3hdoXJFfKeHZl5QGjsU+CP5M,iv:XJ8MHxGMygj7NOb2l4NQDPEwtZUs9MKqH1XBbJbIRGY=,tag:9YMIsIJ0DOaXzQHs41m8LQ==,type:comment]
    #ENC[AES256_GCM,data:Gr+SKw5FZmTdHt0TXYLn5qjJKd7bVXMvJeV0GfOxgSvToTq/MqdocK+Q+WoVOMAWFxULc3lXWIj7Gxgld+WyczpUSBODiX1vJNU1rj4=,iv:S6LROcM0sDgjoTqc8mTM7wb+oAAptvUvJjgzBDeMWqo=,tag:ztTMb9TS42GYqemR5N6I3g==,type:comment]
    TS_AUTHKEY: ENC[AES256_GCM,data:ALH8YaI9jFbVH074PGZDULBJPXrrxgqbEP4/91GCusIs92b7S8tsJFseeyEY8zJCK6WehmOGWHAwJw==,iv:UGF+bua7ltfhnwLWyxZEKv1NKksPuR1KPM+C6l+O1mo=,tag:O/n7Q5vRXEpE1hI+4zxZOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Vm1USjNEeXdNeVJzcGlk
            cURZK0xMKzl0NEI5NVRLUnhWaWQ2ckVlYmxjCjE3U29iSGVzbXRxUHVsUXhHQUw3
            ZTFDUEgwRXRZK05ia3JsTjBQVGFnV0kKLS0tIGp5aVhNM09BV0pXLzFPZHpPSk4z
            RTZZT09UWER5T1dxVEd5YmNFaXpOT2MK/NThD8SgqXwKY9/3hBDnhQzNqc5Uw2Hv
            ckdAXhM8XE24Ambk+mlilbUV49UMXwh9UB4Qvl8mI25tVXLPjTl6AA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYkZHSUFWQ0RGcDk4dGtP
            dlBQV0xKbFczaU8yb3lZWS92R2ZwMTNNdENJCi9JaURHRmxmdmFHbC93cGljUUpW
            a3ZUSCtYMkRXOUkrUXo4ZjlqVWlacVkKLS0tIDdlbmpGdW90dlNUTldDeWlEbmti
            ZzJWRWROZlA4ZVgxanB3Q0VrMXFCeDQK/8C+nDQLiypiIj/W+xuQzg2S0NWewAit
            IOovGE+94XpgM3v6i2UywAfGBt32X5pteEZneRN1eXpg3TvYD0dieA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T05:52:59Z"
    mac: ENC[AES256_GCM,data:VQM+8zUQeI07xtblDFODOZ3nFY+RcejaAYF1GwPxWv8yo4ycQ4nMCAz3giN/CyO/N0KpAQRv+QcUJTgaRLmX6osazhv/noGZyNJWwAh2kNud/f3kj8E5KVMXgwlKgR/NVOgPDjqU8nb24nfgb9/ENhERteboNXwg6NFO+N9zbxE=,iv:oMCurQBB4kNpP7UIFuQvBQw8YVAkKeqRWY6Tbi/Pdvg=,tag:3mPlK9aRzNQBqZVKVPLYRg==,type:str]
    version: 3.13.3
