apiVersion: v1
kind: Secret
metadata:
    name: tailscale-proxy-prometheus-auth
    namespace: networking
type: Opaque
stringData:
    #ENC[AES256_GCM,data:6rLUs88+zVpgUzi+eTx7PJ0yoy9UEpDg8VgTSfQdhlenlFd5HWKP0nNz,iv:d/NBS9717VXAlRqIzCRdvQQf+7CMXBdmqeael9OwR10=,tag:smITQuQzmlXbSVllxlNL8w==,type:comment]
    #ENC[AES256_GCM,data:zX3WMDhLMkm0z0Cj9eqmHOEHthC7qOrQnG7nvMV8p0zVaEUbhEh0Fw72X1lD0uQQN+U0z16Q1Jye8qcKbIVgCvU/6/0ReMx34otUz4Sqf1LB+APMPEitwCu1,iv:DD05Ba7gqGVUbRm5nlKpfStjOEjn9yEOcsV5BonzQTk=,tag:1eGsC9aMGG30z0pkdKgDFg==,type:comment]
    #ENC[AES256_GCM,data:PUBBlDFU5Ii6L6eIal+iVTwpkWvIIIPfu3G9qyW8iKojLJXCRQ+jQaDIP20T4QRD4NdbjBmmKRNA1qZo2RWyrHcQUerfN3dL,iv:5TqPpQpcmyPseEEGw1YlWdc4/aAbLXX0iJSvha2vGo4=,tag:R8Hvbgb60giuQELFcXgnUw==,type:comment]
    #ENC[AES256_GCM,data:PDIJ9/Xn7ef+LCGSTPH39KiD8xwrEBnUbMMvOPLuyZrxUb2sFpoRj2wB6xGTPyyroBMu2FeaG53RrbOPS3hGmCdSFnfNq4RaSUEupm8=,iv:x/0NUIjOH5qfOWe/FWl6A7ynZXJHYGZgxgwQya4SLj0=,tag:dxcq97+CWvTXe1VNGYw10A==,type:comment]
    TS_AUTHKEY: ENC[AES256_GCM,data:b12a/o4TCDlBYCjHh5lj0eBSie8wtO7sZGTyin6ULNY7aPryCWCZDO45D8XWntd0rFnrzANAGshLcvyhAA74jw==,iv:ZPwLQ7vht45HWspdy3iWsf4c3X0PDBySc2yoV0CUhdg=,tag:l36aw5yytKxMBOQYGlOztQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXb1ZqampyeGE3YndaN2Ni
            K3g3VnRWL09HZ1FoUC9JNWZUaytkalpPTkZRCnR5SDRkYkZkckhXZzc0TmNLQ0s5
            S1N6ZENJRmp1TUN0MFR0cWVOQWJJcTgKLS0tIEtpM2M5Q09ObUFJYUVVaUg5R2Uv
            TDVLaEloc1MyL2V5bTlKN1k5SG9pSk0KGUChuLex9iRo45Mfp3/mEm4T0iPJdfq6
            dAGHB/sTmq5Mj78wCVEtC+zjXuQvuebMWbSYgt/R3c8nr/MLbyjbYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUGhrQzA3emNMRzI5cmNh
            SlhLekxMNVFXM1lXOGlNcURzTmhZeGYzUEg0ClFmVS9pREZRMXFhMWJ2dnl0TGJV
            ckR6RGJHbTVDVk1qY2wzRktaaXJ1WDgKLS0tIDg5azRzNnR0Z3BmeHB6TzhjQmQ4
            YmM2cFBUNEYvWnQ5bjQzOENSazAyTGcKNyyHzF+HYDl2tr/+gZi5upBoOkvJhhpo
            u4l33pVG9xvXcMzlabawLFS1WkMzuUxap/brG4pGvyPWphY8+Sjk8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T05:52:52Z"
    mac: ENC[AES256_GCM,data:Fup7jj4hIHBpqIhaSih1OrPyK2H0MeftMDvTGY3x75FdbkE6NeJLGeQnq8STzviCF8AVSk4rJ0dZ3VToamL1Txa3LifyulH0JCxv2LaIGp54yhriGd4e0AK81dkJTVmKjaj+d9kQGRKSPUpH39PMS2DbUVPmzi+1Z5oxF+LRQV0=,iv:953WMes75voTbVF9RdZCtkp1K+cA6s0JeIBkYoo5jkY=,tag:Gz1IXvQr6Qrta5NhN1p+WA==,type:str]
    version: 3.13.3
