apiVersion: v1
kind: Secret
metadata:
  name: tailscale-proxy-loki-auth
  namespace: networking
type: Opaque
stringData:
  #ENC[AES256_GCM,data:1ct8IKaIFNlRmeHub5G/MCNRxq7R2UMHVG2wDWU6JAJz+CDuq6ASpv4S,iv:G6vHvOh2i5hn7fdghS46Ij1qjpKwjI55PdGOzDLInxo=,tag:DLIVZZ+43qynE9dQ7QzQlA==,type:comment]
  #ENC[AES256_GCM,data:XYqJQdXBN/XPPcvudGxp0DQ+yrM5rJFLiTT7yUXnp/u8PfQFEFtxKXYKulHmzFf3YaLZjZLlfs9JDk7QWDPkBT+lcQedi+BPFVipI8PCur4bLbbT,iv:FOKIE95UBgtbLxyipPeAXNZWyGqPrAbWIr+OkNdOJ50=,tag:CvREOtmOfz+2+y9MhQGJtw==,type:comment]
  #ENC[AES256_GCM,data:/QwX6xpH0tFYcz2tIc4WYCAocfHaZpFWnAKGXKPX5zz/doebVphEtVU4doq+H+BtqCd+XVgJ5A6bkDyTwD33d7R4C2/4PuFw,iv:NOZKNpL2n8ZVPo/3Y5KzEyJij6S1HhItw3IRAIS+Oj4=,tag:vznqdBH4mdkimBsXPQIozw==,type:comment]
  #ENC[AES256_GCM,data:Ze6wboTwr8BeY2Hh1J/hcazSa/ZDsnnRiPlaGVvUJUZ0yOfYTuVQXkBgdlJPWd+u0YlrdGj4wPfLUXZti3uP4KO36r6U99Pr0jDpIuc=,iv:kMWG6UeJcfgfOqMMC9ftt72q0qKQuNLbblU/W/2OcuI=,tag:LlshuDmp1Bt1uXDYnBZ64Q==,type:comment]
  TS_AUTHKEY: ENC[AES256_GCM,data:yKimdbFTnUeallDGg4n0Ix14ho/IGwtawr8dEWvpHxbRDuMqjWh1XP3F3XBevEZD+2rVXQNTPBL9O8RRWXRmcDs4cyGOdOefWiz8LzUWzmqQuoBpYW5KDA==,iv:ARd4BhHzYSp9XOB9PrWm2cDarLKmo4nt06rJ1Fw0Ivg=,tag:QjJ1cNy1QyuGKxUeZKLY9Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBai9lbVdVTUpTVmVwMldq
        WFprUVNFenkxRjV1WDVGc2JvM0Zrem1tV0ZrCkRXZ3dzRU95Tm5RWjVpS3RmU0Zv
        RHQ0RmEvc0tJaUVqNkVHZ3MwalZheEEKLS0tIHZsMGdORlo5TUE2a2VWOHpEVTNM
        Vm0wZmwzN0taZmdJSENZUThFblJ0elEKlerrBrJ68VhNvgGlCU5OdADWILAjIDgo
        7pnm9A2qcw+XZa3St+PRpDXOx12V8DGkpUNwM4/7jySDpZQaK7rn+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0STNyMGZEWGYzRUw5TGNL
        WTdlYnpiWkRwamlmMCtzWlBTK3F1aXBHSzNVCjhFZFVSNXNjNno2bUd2N2JEZjQv
        K0hFQjdBT0tIKzVjTWNzRDBxdGcyQU0KLS0tIGt6V1ZVcUZVN1Z6dHdTdDNaLzVY
        SlNIL0NlWGNhMmlabHZ0Q09TL0FyZmcKsDJKSl2hsqrsNVM7yT0LMsoCtMp1k+gG
        r+8ZehaL5utvHmLc0yg6slTG+gblJ69kL72WAgovu/GJwRoufrn9RA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T07:34:06Z"
  mac: ENC[AES256_GCM,data:G4DzJhqRCLCSmYFkOmzjBeKUtNcFUmPKCP329zqUCRNez35cLQ5CazEvDEvuylSf4jqIRyXdUYZgaJv8EsFDb7OXbEkkpNLH3A/XikgYdgMBLm8PQJB2cm6atNKgfmnMuSgSoOqVnUoAycEf7h6VVQFYRrVVO4aUmExzt8OyctI=,iv:uPYJrbghUtSdhcupaS/LdLMqJVJ+ChsLSBnOEAfv330=,tag:UJYWJI87nNEqyrBcFQoPgg==,type:str]
  version: 3.13.3
