apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
type: Opaque
stringData:
  SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:+S5ytwXwtrqfgWA+dDhQpQ==,iv:H1rsmxFWMXhfYpeezQupAe6exwTrJil9SY0s9x9jzRE=,tag:JBCLoKrIfjqDZxnD2kod8w==,type:str]
  SECRET_PUBLIC_INSTANCE_NAME: ENC[AES256_GCM,data:waJUGnYZRnfGPfPgfw==,iv:OgtEFjmyFCCxFJULwBnFBlmWygBIeWmwm5g//v1KwAM=,tag:utM5S96/8UicFLSu/1tfUw==,type:str]
  SECRET_PUBLIC_IP: ENC[AES256_GCM,data:MdFqUI18v/BqGJ1u,iv:kmFLKh0T/62MmJSzcSdrQDEZISiamt5QeP3/QNRRzfw=,tag:cTMHq6lXGqC6BTAZ3koRXw==,type:str]
  SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:gcS8QTRQDyaH0WOblL0XsOKEAA4=,iv:z2iAGOww1QoRz/zbKDtgAL4JIo2tvLPoWTWRKecHiiI=,tag:rFcXP9CbV0AoAf4moGb00Q==,type:str]
  SECRET_NOTIFICATION_EMAIL: ENC[AES256_GCM,data:vZBlyiDs+v6S1tURfNKsBI21Bz6vRHZElPNCzjvk,iv:tjed4rR4o3fROzyt2lLh9qSLpLlriFzGyi3kHkKqJ4Q=,tag:g1GGl2N9Xvrspb9L/SGhAg==,type:str]
  SECRET_TEST_EMAIL: ENC[AES256_GCM,data:3V3gdrfgQkRyMtPSv+fLmjTx3CCU,iv:g8Au7BfkiiHcFKGQZIqo9eD62m/56vV8vAjLs6o4IJw=,tag:8MFwvLw1OP1FGWSJTJBd6A==,type:str]
  SECRET_PARTNER_EMAIL: ENC[AES256_GCM,data:BTYSGpz/56ld/aqSPj/fwMyksQfn,iv:oEDOZvR75Xd4bVDkfM70ec1tTOzjqCJsg1xuVbmT+1k=,tag:F+3JZmJwmXHjcRJbFLb8mg==,type:str]
  SECRET_LDAP_BASE_DN: ENC[AES256_GCM,data:851mWDRqEg5g+pvD5MjObBjdCuxBAg==,iv:j0jbiP/5uaFOBtxoQT+JXOuFcPy18cuCZ/kGYAetOrU=,tag:eGXMhm6mH2DNCnrjE5NlGw==,type:str]
  SECRET_SMTP_HOST: ENC[AES256_GCM,data:Zbx+dXWCiW+eHFGBL1bYPexEv98=,iv:bCTLGSp9tjG+38Qqtny/qsRWPIoL+DMM6UCmJSil4mk=,tag:HMV3hN99oDd/1hI7IuCquA==,type:str]
  BLOCKY_VALKEY_PASSWORD: ENC[AES256_GCM,data:QotXHObmOV1NOy/n0IrxWWRdZXJuPf2lMoZN6xVP+CdJhwvTwQVACMa7I4/Ey+tSl2Qd10PU7yRD/2uAkRP4nLK2rTECUiO2c9gqIEJEtt4rA93hVyVvHgN+vrklgNDGu5uwtA==,iv:xptLvTdbPfHYfBItpEGXSYuB4k5hPmKOYnHbHe7TlaQ=,tag:DZM0+9IbDgSPM5LWWYrwWA==,type:str]
  SECRET_CNPG_SUPER_USER: ENC[AES256_GCM,data:0uJOW1+4lzw=,iv:H9cTfb3nYN14HcZrtPGR47vwvCCJDRNAlEejBgOlqe4=,tag:DYjXdBE+T82XRWFQR16SlQ==,type:str]
  SECRET_CNPG_SUPER_PASS: ENC[AES256_GCM,data:IoL/dY3XhHl8CZ53ZDE+berUwA2t1SMVcbx3PICnqtgUFLIjMLpPDFrrR1HJZGnrLrEKIi8cPnGRig/20B2hqJ0biY//1h5BpCeDep4aQCGeTznC9gtImIjtf0dBQ1u2f5uX9byW9yZ5m0h3dr0mQUFrGoXsPm0illwzAs7dV9w=,iv:me9T9kHZ94+CiDKUSom5/vaXUW5etDdGx2PU4GOg+KI=,tag:X3CiTd7DX0umBLQ987um8Q==,type:str]
  SECRET_CNPG_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:6sz0pA==,iv:AD+wIPRLykBaz4vpflMo27DSwt2NRWwwIN5szqmMoj0=,tag:NOSs4vdY6gNbCYwyhY5/SQ==,type:str]
  SECRET_CNPG_MINIO_SECRET_KEY: ENC[AES256_GCM,data:vzArIuWCPqAxluoQiVlbeGKnxBmRKGvNwzIdfkPnJnW9ku9GwGhBCw==,iv:iE8AOKR/kjOdivjA7d6755XfG6Fn9BI0VIaGxCeMgVg=,tag:as4lAxDgkKwfTvxnsDuebQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ2prVDkrQ1ZIekVTZzRD
        Vit5c09HKzNQUkp4MnpZQkl0Ly9JNkRkODJjCkd0RDdPTXhWdk1UakdXbnd1Rzla
        NEIvTXFvL0NrU0FuRC9rdW1XNkxDM0kKLS0tIDNjUURPZ3dUL0x6QmhVM05iOWtG
        OVh6dnRReXFFQ2MzNGFTK2RlVmMyRW8Kp1c1gDbclqtffGY7fdVIitq85InadYBU
        mk1WinIth8KVBxqln3/rjTdggv04HhpUJEqWPTCHsqRoKRyUARkTQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZjUvc29wa25Bd2E4MUtG
        ZGtvVjFrcUMya0dQbGdTSkV3V1BtbGpFYTB3ClA3cFlybHFHVS9lQmgwYkFzVUV0
        WHpMTnBFZDkzYUJRbDNZVC9jQms5ZTQKLS0tIHRHQTVhWGFNQ1A3emQ5VUErRHdW
        eE85WkpGbHRiYSttY1BIMWF2TWZTSTAKcz91SJDuwVjIispRaLf27TQzqD8+JZmR
        A80Bd3tanLGBP3ImF4cqClsf9mICljjSlgXz0sTZF/W07VOD9eIdgQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-15T22:36:19Z"
  mac: ENC[AES256_GCM,data:4Te0/g6XXteu04Hd0CTCjruivUQjV3fgN+UNaHcdmAxtJei1OMON/lzIFsjL7Qg8s/YbWBw14b5jqwauLQrCCnGJ0pDcFLbccGJ67rtdsaNCFvHjcuKHua5HuVXMXlWfdUdNWXGOWYPsRRAB8yDwOkoIEJQKVwFlfyry10fLdpY=,iv:YU1q0mO15uxL5OGexskhhvZjF3ylkOBAkD/o1su10m4=,tag:ZjvEPIkGejfj6T4XC7/mXg==,type:str]
  version: 3.13.3
