apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky-valkey
  namespace: networking
spec:
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    controllers:
      valkey:
        type: statefulset
        containers:
          valkey:
            image:
              repository: valkey/valkey
              tag: 9.1.2-alpine@sha256:a0dbf4c1d5708782907c10e2c72deff317518518b5288a58416981d9db95d30b
            env:
              VALKEY_PASSWORD_FILE: /secret/valkey-password
              VALKEY_PORT: &port 6379
    persistence:
      data:
        type: emptyDir
      secret:
        type: secret
        name: valkey
        advancedMounts:
          valkey:
            valkey:
              - path: /secret/valkey-password
                subPath: valkey-password
                readOnly: true
    service:
      valkey:
        controller: valkey
        ports:
          valkey:
            port: *port
