---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: overseerr
  namespace: media
spec:
  jobName: blackbox-http
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
    path: /probe
  module: http_2xx
  targets:
    staticConfig:
      static:
        - http://overseerr.media.svc.cluster.local:5055
      labels:
        app: overseerr
