apiVersion: v1
kind: Secret
metadata:
  name: blocky-tailnet-auth
  namespace: networking
type: Opaque
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:xvfFimBumJjQmzfDBKgB3TMES31bTPAaHpBKtRmfOD9msk9wBXLQyQ96UjQNNT3LSPmJJ8agDfekDL5Gh640qU1X5lEVFPWUz+hbWPFBY62m8DqbtdmG4g==,iv:R2c4g85kr9jXt/zVo8LTMKo0+XWIgmyHpycvGmAN9Xs=,tag:6IF03HDUba4Iv5ODgkT2qA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaFZFWG1EUzRWVkxiSlF4
        WGlKUnBWYUF2aGVvTThoQ1NkaEcvR2FxeVE0Cmp6WXRMTUpSaVY3ZjllK2NxTnd5
        NU9yNHRFYVlyWjAxbllYczdjYzJ3QjgKLS0tIDNHNVp2TCtxbitCcXY3cHVtZXNE
        OGFBbnhRL0d2Mmc4MzRaeWp0S2hrTVEKshFM3cdQuCwNSiBkC45wd7ohFO9do4pt
        jtqR39rKbbFyrB3FSo40Ft5oUEFGpz02F4wYp8492tBmiCI6ylGVlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNWxGaFJkQytGQzJRY0Iv
        MkQ2UG9XTS9BTnhSbFp2UGwxak1DYlFmcmc4CjlPaHZVUzhpR0FaTm1Ucm9NOEov
        RWlmSEhhWEtCRnRjeXRaUlMxTUJhRFUKLS0tIDZyeHRsNFlBbENVQ2UvcllsenB5
        bEMzVUxjUWtwMlZpaW9sUmVQOVZLVEkKatY+dqw314IE8p1apYA3qD+qMhXF/dSD
        +P0L2p9ZPZgg/GbVV8UiKw4hu1JS8h6xsc1WL5woTH7bjq9WSsfktw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-02T07:17:59Z"
  mac: ENC[AES256_GCM,data:cHF+CKcjgE/ZCqDm/ITi98PDnu6M8to8654iAo6HnRVe5NSx33yc23xiL9qb8rh3QhFZH/4y/RUC0aSZlkO75WFv7PQ5z/TmuwKgEMHDGMvMAa5UlauWvxMDy4OjT/Favnr+Q+cqs0CPmZuYH3kB2I6PU+Gp6PFX0IAlIzM7brA=,iv:CT+hXzSWGF86gb/VLOCeZxTyZ0loV8P2JNXmcPCfCF8=,tag:g2WrtmBqvNeuMx1/POCEqA==,type:str]
  version: 3.13.3
