apiVersion: v1
kind: Secret
metadata:
    name: mqtt-recorder
    namespace: home
stringData:
    MQTT_USERNAME: ENC[AES256_GCM,data:vMxz55wG5CCK2EjMfg==,iv:CXHbOs1cXfxRuIP6zq31ehClovDm36i1XSIOgRYM5vc=,tag:FrTR9Hz7/0q4xVsNxgO7TQ==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:uLGoCIZv6/RoZw==,iv:A6VbRAjndGYHWOHmqI3/3BbXFEDFk3BUE4unEmxqMxs=,tag:dZliW/qwddATOUw32crvkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWmZ6NnBhU3hYOFQ1a3E3
            NTVsNU5rK1lGcURUNUlKNHdZSkpld1dkL0dBClhRa1d3eUNzR054UFNJWjJVelVs
            MVBYbDdzdElXQ0RxUWE5bEdwUU1FTWMKLS0tIGkrRXV3cWF5elFoaHBJVmpZV2tK
            UElkTDhCcC9UOGVCb3ppdHB2RllxR00KKABzm+JvcvrTLr0miSyFJnpAZu8LLp+z
            qYzzE0Cr5p/Vse5YO79V/Q7Y/27cqrqeBQQWs6vSCz9EtBsEk9aLMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQndYRHhBY2h2ZFNZUndj
            MW1GdFAvdk1JMFlLM25VR3plVENWWW1ZQ1RrCjJScFFmb2c0KzVCNGFURmYyaGhT
            R1BWZm10dUpsenBlRE1RNXhqWlVlb0EKLS0tIHVxdVNkWllpK3dtQTFXWGJmVlpu
            OS83cWhXL0hFejlOVDZXa29GWUVKWGMKil1tx9SdBjR+cM5Hk+dI2n2X8vqJx8da
            Kcp4VR2PyC9YL8bWjeqnHVS660wxVZlexa0xQcmU7FKZJrno3h2Rpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T08:52:41Z"
    mac: ENC[AES256_GCM,data:d3O9F5UAin6g17w9xOHgpMNn0O7aN6trLtWdrxyhewh2ML41tAtPN5atSuXQCkHjUVNOeJgy8tJfQSmcRO/TNCCYVA16YRQfCrFUKwi1Y2d2N39jJFR4nIAQoVuOfC8njIWy56n79GUURH01qT/gfYHU4rwkrcN2b3ceXmuQWu4=,iv:JXphH4QbpAinsKsj6Zg0O64NpbiYZcYSlhASUsw3L1E=,tag:kNY1+mt5YrPWCPde6Ojd7A==,type:str]
    version: 3.13.3
