apiVersion: v1
kind: Secret
metadata:
  name: mqtt-recorder
  namespace: home
stringData:
  MQTT_USERNAME: ENC[AES256_GCM,data:xe/JWouJbu5Vc06o2g==,iv:OhZiCwpPNsIpEz7HzRSTkg77si0PMLNMUjBuqWY1/gc=,tag:4DiZF1/sEgFhA81LBKRKHw==,type:str]
  MQTT_PASSWORD: ENC[AES256_GCM,data:Jv7mtuZQYVj3biXEWsT6XX/aG1MmxTqesQ38iyLwH4r4,iv:av9IIU67C1clAyGIhSRuASPRw2aGdnq342pLkCbwS8g=,tag:fKiVBjnsOgUcFSe6n7zSKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MjRDY1ZZV3Q5MGF4ZzlR
        THQ2aTZkbWVUSnJtMlArTEFhSGx4ZlZhR1QwCkNsdytnaXdVT2JLMTlLYnZQYzFt
        RjVVOGtQQUk2U0lOa3Bra294cURqMlUKLS0tIHlsQjRiMkpLVG9DTTFuM3Z3eDRJ
        TXBoS0xidm1Idlg1Y1ZIaGwxVkYwcE0KA25k/HVpljOwFWiT4Pg3qHehMYS31tTJ
        ii61XCVVVGKA3k+dNgl7drY7TRR5YSCSeWP2bOQsi6nGs0MuPe2/wg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcThEdzRPWDlBZVIxeC9q
        WHA0R1U1cjBqYnlKdGIvZUpZV05BbkEzTW5VCk5lWnFVb3F1VUx0aFVDUkRLRjVY
        RFVHV3AyQXdWU3poalY0NElsdFd3MzgKLS0tIFBDRjVZL05wazVEZXVUMkVFblp6
        RW0rVVl4RmJ6N2thQkVUaktxYitOc0kK18+X5n1vh/ObKoJmSqkPhtKr7Nkgudyv
        1wTsSsXah49P2Q8xLSwzQ3EsM2CvmB0BRCRyZTT/o997heu0DVMDHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T08:58:31Z"
  mac: ENC[AES256_GCM,data:U3o/W9rrcJfbFMGVgyLTWjgEqqDtJ+Fc++zQ+mlYA51eBJGZut18G/MPSTy0RxO3oZvOzuZZsBSsD+vljsa1NOebwN9GozaDS2olSOmFfFwK4hq5m4nhxwCgDRqIXFFqRSqzZxZgeEmGT3+tm5SDYbGXAUOTpmU3X4+qUs6XC4Q=,iv:2Y9W8+KWG527tsCRjiekmibLLnZintt5GuXeBLPBUNw=,tag:MWpeTWpXyS/0DXGOYumW7w==,type:str]
  version: 3.13.3
