apiVersion: v1
kind: Secret
metadata:
    name: authelia-db-secrets
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:TEtHuPP9Chg=,iv:RcPrbZ3WnnvDCo/S2Bwslkb2R9fG4pxTcoL3JORh/cc=,tag:93Wvm4NVQ9pTQhR3KveJbg==,type:str]
    password: ENC[AES256_GCM,data:YYzVnG4DBCF4YuNGBf1oExCGPCCAXsnQiaf4qSjC,iv:4oMrnQYw5TW/46CDCoQspG1++HVRSAsfnm1ec4Bk07Y=,tag:lmmMyjsqS5FPPTdfkI+V5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSWhkcUhtVG5NMis5eDYz
            SElUc29UeGlHVkZvN25YaFNPYnAySHllVnlnCkpKcDFjUU16SWNpNnhNR2xGK3c1
            N09qNms1TnZHd01SSERDQkNlbHQ5aHMKLS0tIHlOZW51bm9nR2JDelBGNjU4QU93
            TUxlMEdUeEg4bldDSGNBbWhKTGh6VWMKEJyB6LCZEJklJVpciS5mBKl7ZGEULPWO
            NsKtp05mawITDyVRb14XeWQpDTtIxwmIgW8GAAG20HQAKKfYl7YH1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQM1FNeEhzWExPZUF1UnBD
            Smw1eXVremgyanNOc1dzeFdHQzFSVG5NdWhFCkpPMzlid3h5d0wzKzgySXpPbWFG
            NFJNNm9ZcHI0M0t4QkhPZFAwK2hDdVUKLS0tIFg5ekdVQWcxcVRFYlc0UEdWQUdp
            Y1RmM1NCODgrOGtIRk80YjNSaWM0S1UKzwofwAgdFPwwKlV8ZnqmYh6jE8BML4eO
            MO8z7gDeIu+LhCceMg58i4SCixGW1qLbrEwJ51UUk0+WP9tCyqqGqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T01:29:13Z"
    mac: ENC[AES256_GCM,data:ZqW97PjMxirXZmFEyH4z/vU8T22NUcZ01csOaH7hesF3hPvQAi4gjGB2rMWR2b4V+xt5kJ5lEY44nAfJ2OiMH50Vo7LDUIrCFPrby67y/P0YrEBkulhX7VDAjLmHwkz7jVtjyOgt0PnovSteOlJmEgFCV1WSgDcxp10bNI8YHDQ=,iv:Q392OWeEChb16IfoxejkOu8Nqs8f3qTAulHvUO8CTuQ=,tag:N3r0Xqw8n5jPEIQjEhqWoA==,type:str]
    version: 3.13.2
