apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-s3-tls
  namespace: seaweedfs
spec:
  secretName: seaweedfs-s3-tls
  issuerRef:
    name: internal-services-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - seaweedfs-s3.seaweedfs.svc
    - seaweedfs-s3.seaweedfs.svc.cluster.local
