apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-credentials
    namespace: seaweedfs
stringData:
    admin_access_key_id: ENC[AES256_GCM,data:M3uY4H0kobtbkNa4kmtBPJXKYvZYqMSbzlJCVBQDGdw=,iv:Sr5WYM7eAhVugU9y5IxOkK5UZgl1CFyesi5TKmKV3Cg=,tag:e1D82F1zrNzjeMinY7xwPQ==,type:str]
    admin_secret_access_key: ENC[AES256_GCM,data:Ok9r2VJSN4amY/GPj/LgP5ErW48bf3Ky6g5IaARWARu5P6x2XI/BWOevkLwngSUj/T2RTP+MjEDmytf1848m0g==,iv:CCedPbj/LflJpORC0WPaHWW/Rip2pdl6QZC3pLsunQE=,tag:gm3346bKapTClzdfxVczIw==,type:str]
sops:
    age:
        - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5b3FKdVZzTHdHa3YzOUlH
            S0dVaXgwby9SMm8rRURaam5hWTlCQktYN1hBCjNWYnJYZEp5S0Jtbkk0YnhzSlE1
            ZTh5WCtWTFlub1VPcktFc2JNN1VsZTgKLS0tIEtMeGMybjhjYzRMQWJmOW9MK3k0
            SzJQSHJxVnZWKzFhcThocEdKai8rRWsKu7D64HsHF58M25145CmEKOSZP4bfzxZ7
            2ufH029QrhGeN7nrQAeTP0zrd7zDSWXUs25Z5VgjZrIy+0jnFMiDeQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQ0dVV3hCcHZYNngwRnZE
            UE83eGxiWTN1UkE3NTUvTTBTN3hKWEZPNGg4CnB6V0o3dHZTRWhBTnJLdnBjR21R
            SEJSbHh6TGowekl3RGI1dHRJYXQ4Y1EKLS0tIDhxM0UxZFNBVEJBOTk3Vlk2c0tX
            WEQ5TU1VdFhCYWEvUFV2a3dUUUlKM28KG/9y47SYkTXK9GGuNMfKb15ZyMgUX9rZ
            hKKAPAnfO54zlkN1A7uis/UN6NeTFJ66As4FhxHA4ZlApxqIGNr6uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T22:55:44Z"
    mac: ENC[AES256_GCM,data:LSoqK4ci0J2889YkJJI2F4j9GxSSVXX0NK+eYKy2eWlTX8sXD825PkgOXYL0A1MnFdepOfJeHgWhjjOUR5XPNFtpVSs3T7Yf2AFZHWeAJc9CVWHOcVnsyQh9S3zbVwX4S8t353kuoz4axo6DsPF7QRlEPUrDD/XWatMpWsnTdQ0=,iv:AAAyCz/di6eflGDFGu5LX+suFkpLjSUcyXL5jkpG8Ys=,tag:6CpFlBPLmGwMXux3Ei7tbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
