apiVersion: v1
kind: Secret
metadata:
    name: changedetection-io-secret
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:LojpJAMjsdjG1G8t3l2TYRliHIJqG1PQeb9PRAYw3imECFkFwOvNCDDLuWzfT5remWT1/VUfPf8vrq9Z7LEs/A1MTXlDbTpZ,iv:FtJN2txsSZi+dOHVUKoPLeYksd8GP5ckD/GtOiWnb9U=,tag:msQ2GXmEfIN75zvybzuxOw==,type:comment]
    #ENC[AES256_GCM,data:VmJl7HPvmL/jEZTp6r/2Q66myugyvFGYSON0qtPrlJ37H23rnySDLVZv7z0i+u9T4n5+KgrJa2D4fBdjvaMqktRtOD6ik6hzfoN5OIqRqQM=,iv:m0yCSyEqoHHvkW8CadoclWNbFGv5Fptzbl6xUYX4pNw=,tag:5fAbK9mcTS6jwGLJqfmYXw==,type:comment]
    #ENC[AES256_GCM,data:Z6HcSjkVQimQs814k5D6HO3x87SK+s+O/Gur6RKasyViMyaDnfDTACBakqaPm5qoqO+/DqOoqouPdcthv34nUAa4WzI=,iv:9AngTGC/Jd9S23j6rAuh/jdB76KdgZlYjHqBPCParc4=,tag:U0uQpzL5ww+bpr8a8DT9dA==,type:comment]
    #ENC[AES256_GCM,data:+pTKxSWaeGKzijItwAe29ZWXgd0QfDzILPLww3E5HhTyd6WN9wBbOgGwMvmokPrwwafjvkIMrn8YHY/70o7AJ6+/a32gqRk=,iv:5cupgqj/18WIotzgAze2nr+GFwedjCd5bzr1YvU13No=,tag:CBorK82jL+mO0930LH234A==,type:comment]
    PLAYWRIGHT_DRIVER_URL: ENC[AES256_GCM,data:iQcokdKh/IuB4WOsKJ6DlKr9PRZAy1CZ6RI+wKE8RmBF2wnfEjNtcTfF8oBb4FT7E8NBdO004iSgpgwFI3jt3PIHb1ZynvJpBStzoLf27a1QNDpkvUvFwHh4jeFgOhoVHLp0cuAVX/E9k6ZI/TMk0Xc7ehhJ5kCy8yZIur8n4yiEubhL96renfDvEmTUZ8w=,iv:dB5kv0KWAduEYSgngr1iWvtzLqWcdascjLDZJRKJSYU=,tag:UhabD/TtNCmi7+VyWjzHyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqalA3VTlpOGsxZWkyMkNS
            NElYbFROK1VoVmRYaVBzZnlrdVoweFVNelhZClRyOENXbmFtbVpqUEZGa1BQSmxo
            ZmIyTlJrZVVwcVk3RUVLV1pzMDlVUTAKLS0tIFVLMFRkWFM0UW9odGpRa3c3Qmxn
            VnF0bTl2UnI0WTd3dmpWbWVBSEJ0S3MKPxBYrK/0qeYBSxH3qFqQZe07hD5xgfxQ
            PTSLP3wLYMcUZYpRipXrX/6Vz44VNHKrmbF/Nw8oPzMh598yRmlaiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNUtjV2JlRnhxWWk4bjlM
            czZJSFN5cVlrRkFEaHNVUTB5WjRaT1VCdHlzCjRqT3pnanJROTZPZC9QdGdZZkVB
            Wll5OUVZdFBrcDJHZFdvcXl4K2pyS3MKLS0tIGttVENYMVdhUUlONFlISEdFVjNC
            aTdNTTRNZVZPaVM4U2xoMkxPNEJjeVkKlUNJ99lOJ1Bns2qB8PUT6DSRguabZTmC
            eFwGrsTbsZrIyX4Ks38ETgy+arQNZ8hUf5883Ihi4vh8hZTQi9+qow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T23:37:21Z"
    mac: ENC[AES256_GCM,data:NORx8F16L+sTr7hEVtgQyuoUCiaVthfr9OTspl4ayjNU6AiaHQ1CdpWSXvI97CsugIy0TS1Urhg1VBt9ZXoix5OBnfNv8Od6Guue4VnpcCmBQm7lsoJGjZUsRJ8p0OBJFGMvj3Kj9WGON/KTxjVFZ0RIPu1dkrXo3fOAxjC+uOs=,iv:TC3IFBFUU9hXeAxBrHwXq2Muli5wlSNASiNl9zeNk1w=,tag:e5kLAgNf2QXimA3Fl5th6g==,type:str]
    version: 3.13.0
