# IMPORTANT: This file must be encrypted with SOPS before committing.
# Run:  sops --encrypt --in-place secret.sops.yaml
#
# Values to populate:
#   client-id      — OAuth2 Client ID from Google Cloud Console
#                    (Credentials > OAuth 2.0 Client IDs)
#   client-secret  — OAuth2 Client Secret from same credential
#   cookie-secret  — 32-byte random base64 string, generate with:
#                    python3 -c "import os,base64; print(base64.urlsafe_b64encode(os.urandom(32)).decode())"
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: monitoring
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:A2Ly7eE6erpH8JcURbrjJyGGgFew9CLh0qjFzryhXKCg1FRGTH2tBuaFuf8cwrTmHLvRNNcF8B80232/HA8tFdqwwT649khbXQ==,iv:T9MdrxUJqtpzEKtGDCImhLBBGnMjuFxlaWoc5mE9x94=,tag:ySFebacLH3FSmALoPfxVmA==,type:str]
  client-secret: ENC[AES256_GCM,data:mFu5Jkr4kRshjCYtzhYTNLGPJaCorucsoIRXyNCdV1iMmOo=,iv:B0c/I3tEO9LPqdA+EIf4lVV4yuYeiFJLCxZdw4N3LVY=,tag:QHDo9U+002LxKtz4Q+SJMQ==,type:str]
  cookie-secret: ENC[AES256_GCM,data:48aObhFufPMzi+O6VB8drkS98iKm40jp+1w2fYqiPrMmwQsruIeQK6NZgJ4=,iv:AGswqXCKqIrKEC80Yoz2I0v7PWHkHKMEGhzy24zAqfA=,tag:eLX3msvti3yI/jAdehrQRg==,type:str]
sops:
  age:
    - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTFA5aDhjYWxacUlaZW1V
        T1Z6S2pHV2sxanpCVVdtSGQ4RXV1dklqVWtFCmp4ZkdZU3hKK2twc3Fpc05aVWw4
        VmdkdGY2SEdBWXE4eWRjSjZrSlVGM0UKLS0tIGJqcGc4bVZGWmo2bGxDQk1Mamdx
        MXNFYmFhL09rcXZzeWR0L2tBYUs0dG8KEYnxqnGmaXe6aiH5Mu31YY4R5IGEvDBd
        v1MdnYLUt45HpmMTGm5kOibtuqUREnTEcCIewiGKuWJNN2s41FhhNg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbUF4RlRLNkxMU01ic2dz
        dnkzOFN1cmJDLzFRbnZ1cVF0akwxWjVFZ0U4CmxLSkRvK3UwdW1aQUxzcWFhenpI
        U3NQSlMrRllDUzNVN3VRdlNoTHl6NGsKLS0tIEQyMnNZUU1HRW8vMTZmQUdsbnRq
        NndGZmI3SUgxYWtHcVM0MXNvZFl5TWMKYU09fzmOY/ydc6m+unqfREdNP/JqkQMw
        E/5VuSJu79OwMB1sOeellrCs3hh6o2bfurW4iygq6ZM2Zt0/w7BQHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T05:20:50Z"
  mac: ENC[AES256_GCM,data:KzmmOof6Ez792Hk1J/+Nlt85Xs+1nAyIljYizf4Iapp4w51r5MXXiUpyNlLXZ4naTMXEEo7tMpTRkox3IeyAXx1Z+waLk9xLIiUd8SrAP7DyE0z75yab3xsofugQmd0q9rykdsuMkDTIkZQXCPI9THNqEEFniAEcK5lcN5OPtkU=,iv:0NnsAYaJNW35IAvAwLfyqE8o9IpMwnQGHV2Exf6og/Q=,tag:3NOOA+k2ggOZ+VOH3KHDug==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
