apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/control-plane, operator: DoesNotExist}
  prepare:
    args:
    - prepare
    - server-plan
    # renovate: datasource=docker depName=rancher/k3s-upgrade
    image: rancher/k3s-upgrade:v1.35.4-k3s1@sha256:b5196d2799af4baa8aefb1653f2828b9145b53eb21d8508cec04f307eab3e11f
  serviceAccountName: system-upgrade
  upgrade:
    # renovate: datasource=docker depName=rancher/k3s-upgrade
    image: rancher/k3s-upgrade:v1.35.4-k3s1@sha256:b5196d2799af4baa8aefb1653f2828b9145b53eb21d8508cec04f307eab3e11f
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: "v1.35.4+k3s1"
