apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/control-plane, operator: DoesNotExist}
  prepare:
    args:
    - prepare
    - server-plan
    image: rancher/k3s-upgrade@sha256:11b97acdff08c22cb001b5f6bbff4f34d1a9c70e40f9605c2c6b5d5451bc508f
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade@sha256:11b97acdff08c22cb001b5f6bbff4f34d1a9c70e40f9605c2c6b5d5451bc508f
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: "v1.35.3+k3s1"
