apiVersion: v1
kind: Secret
metadata:
    name: changedetection-browser-secret
    namespace: monitoring
type: Opaque
stringData:
    TOKEN: ENC[AES256_GCM,data:qsUZBXrp4SRY/rF1mCgspzr1JYJm3ioOxlBfqk/CPakeRrS+88Hf7rp4SPV22jEoB0XNaWNralL+bV31nMZp4A==,iv:PalJWGOBIiq6PMwvtqhnvSpncQQmZ+t32Fa8ouCgoCA=,tag:enwAbw5YFCY8H51MnQ4lkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UVgwdEhxclNmWTZKcHA2
            SXRGYW5Qd3h2b0sxTDZoUENPa2FmNTJHQkRRCmhncjRHeWVPa29rWVI2eUpsbGwv
            WFh1aFhvREdvZkphaTFOakVORXdCa00KLS0tIGlxcXJyZG1UdGlqa1hNQ245aTEw
            SDJzc0ZRSGxMUUVUMktHMlRkR0QxdmcKHS/ZjRl4cSERlcWecuo1Ix5Y0tzYkXXG
            lworkVOkBc+S5jF7AEC9TOo7Poyhw05gAJk7U3+efFKpSTvdA3RqCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NHYvYm5SS0xCZzUrRmZr
            ZWl4SGNZUFVFWjBrMmgzWGVmSUxMU2ZpM0dJCkJJSW5IVnFBV0tLbWNEaGoyNTBp
            QXh6ZGhNRS9idTFqaHpyVi81OWh0WFkKLS0tIE03VE1wZ0JsdVhlNE9aVlJPZlpz
            M2trdHVud2lycWNnc3NUZkdUcm9UUmcKVnQQ6IryekI5lGJGEifJOfC+4EXy6HC/
            A9tQIlHJX1cxt6w8l8cyiyGzQ2wyt16FiNySfANvjrM62IxSX31tNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T23:15:13Z"
    mac: ENC[AES256_GCM,data:PgZKMrolcRqF0BusACg2K2OnkRDjmi89qmEuFi8WblsVJgKw26JJXV+xgm06IX26TTiGi8/ZnV5jpMbhlrYuDlkuqEgLGlN6SxRXZ92wWteufBIUsmw/hGfpv4bxmy1avbWk7tBsAD/oJtkUwIJYuZbGqUJUDmuMJDRhtpaOh+I=,iv:71oLO7jkCRrOMZhJdTyjjXHfDBobU1vNsom1XGl74Dk=,tag:7/I4kXE3b/26DaYpld5cKg==,type:str]
    version: 3.13.0
