---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: home-assistant
  namespace: home
spec:
  jobName: blackbox-http
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
    path: /probe
  module: http_2xx
  targets:
    staticConfig:
      static:
        - http://home-assistant.home.svc.cluster.local:8123
      labels:
        app: home-assistant
